CREATE DATABASE ShopDB;
USE ShopDB;
CREATE TABLE Products (
	ID INT AUTO_INCREMENT,
    PRIMARY KEY (ID),
    Name VARCHAR(50),
    Description VARCHAR(100),
    Price FLOAT4,
    WarehouseAmount INT
);
CREATE TABLE Customers (
	ID INT AUTO_INCREMENT,
    PRIMARY KEY (ID),
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Email VARCHAR(100),
    Address TEXT
);
CREATE TABLE Orders (
	ID INT AUTO_INCREMENT,
    PRIMARY KEY (ID),
    CustomerID INT,
	FOREIGN KEY (CustomerID) REFERENCES Customers(ID) ON DELETE CASCADE,
	Date DATE
);
CREATE TABLE OrderItems (
	ID INT AUTO_INCREMENT,
    PRIMARY KEY (ID),
    OrderID INT,
	FOREIGN KEY (OrderID) REFERENCES Orders(ID) ON DELETE CASCADE,
    ProductID INT,
	FOREIGN KEY (ProductID) REFERENCES Products(ID) ON DELETE CASCADE
);
